[project]
name = "genome-minimizer-2"
version = "0.1.0"
description = ""
authors = [
    {name = "stacyshcherbakova",email = "stacyshcherbakova@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas[pyarrow]",
    "numpy",
    "torch",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "scipy",
    "biopython",
    "wandb",
    "huggingface_hub",
    "marimo>=0.17.6",
    "nbformat>=5.10.4",
    "altair>=6.0.0",
    "polars>=1.36.1",
    "cobra>=0.31.1",
    "pyarrow>=21.0.0",
    "statsmodels>=0.14.6",
    "pydantic-ai>=0.8.1",
]

[tool.poetry]
packages = [{include = "genome_minimizer_2", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
